# Start with base image
FROM openjdk:17-jdk-slim as build
# Add Maintainer Info
MAINTAINER "Amit Maindola"

# Application's jar file
ARG JAR_FILE=target/*.jar

# Add the application's jar to the container
COPY ${JAR_FILE} app.jar

# Un package jar file
RUN mkdir -p target/dependency && cp app.jar target/dependency/app.jar && (cd target/dependency; jar -xf app.jar)

# Stage 2
FROM openjdk:17-jdk-slim
VOLUME /tmp

ARG DEPENDENCY=/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app
# Execute the application
ENTRYPOINT ["java","-cp","app:app/lib/*" ,"com.optimagrowth.license.LicenseApplication" ]